# Generated by Django 2.2.2 on 2019-07-01 13:03

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=16)),
                ('picture', models.ImageField(upload_to='D:\\development\\git\\sekm-maps\\data\\images')),
                ('geom', djgeojson.fields.PointField()),
            ],
        ),
    ]
